### ISSUE TITLE
Domains of hasTarget and hasShape

### ISSUE THREAD

**Issue by FabienGandon** [Wimmics/solid-start#41]
The domain of hasTarget and hasShape are defined in the [ontology](specs/solid-indexing/ontology.ttl) as:
```
idx:hasTarget
    rdfs:domain idx:Index, idx:IndexEntry .
    
idx:hasShape
    rdfs:domain idx:Index, idx:IndexEntry .
```

This is a conjunction and therefore every time they are used  in a triple, the subject will be typed as ` idx:Index` **and** `idx:IndexEntry`.

We should either introduce a disjunction or agree to use them only on `idx:IndexEntry`

**Comment by lecoqlibre** [comment]
We agreed to remove the `idx:Index` from the domains of `idx:hasTarget` and `idx:hasShape`.
