### ISSUE TITLE
range of  idx:hasTarget and idx:hasSubIndex are wrong

### ISSUE THREAD

**Issue by pchampin** [Wimmics/solid-start#42]
the current ontology says:
```
idx:hasTarget   rdfs:hasRange xsd:anyUri .
idx:hasSubIndex rdfs:hasRange xsd:anyUri .
```
This is incorrect. It means that the values of these properties should be **literals** with the datatype `»sd:anyUri`. And semantically, it would mean that the target / subindex is the URI itself, rather than the resource identified by that URI.

**Comment by pchampin** [comment]
The correct range for `idx:hasSubIndex` should obviously be `idx:Index`.

**Comment by pchampin** [comment]
For the range of `idx:hasTarget`, I see several options:
* we set it to `ldp:RdfSource`, because the intent is to point to RDF documents, but it then restricts our vocabulary to LDP- or Solid-managed resources, which seems overly constrained;
* we leave it unspecified, or set it to `rdfs:Resource` (which amounts to the same), but then it is overly unconstrained;
* we mint our own IRI for "any HTTP(s) resource that deferences to some RDF syntax" (I didn't find any matching term on LOV)

My preference would be to go for option two (unspecified) for the moment, and in parallel we create an [erratum](https://www.w3.org/2001/sw/wiki/RDF1.1_Errata) for the RDF WG, suggesting that the `rdf:` namespace should contain an IRI for the concept of [RDF Source](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-source), and we eventually use this one.

**Comment by lecoqlibre** [comment]
Done both. Used option 2 regarding `idx:hasTarget`. Waiting for the erratum.

**Comment by pchampin** [comment]
> Waiting for the erratum.

In fact I raised [an issue](https://github.com/w3c/rdf-schema/issues/29) instead.
